# Generated by Django 2.2 on 2021-10-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolios'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fnamebet.cc%2Fphoto%2Fperson-clipart-silhouette.htm&psig=AOvVaw3yU0fmxbLnfGnCKtb5O6j5&ust=1633309893272000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKjo9NSHrfMCFQAAAAAdAAAAABAE', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='portfolio_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Ftechcrunch.com%2F2016%2F05%2F10%2Fplease-dont-learn-to-code%2F&psig=AOvVaw3Zh4mTcwkCNIBmXWPLcyZY&ust=1633309987759000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMi_hYGIrfMCFQAAAAAdAAAAABAD', max_length=500),
        ),
    ]
