# Generated by Django 2.2 on 2021-10-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211002_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://wikiclipart.com/wp-content/uploads/2018/02/Child-thinking-reflection-thinking-pencil-and-in-color-reflection-clip-art.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='portfolio_image',
            field=models.CharField(default='https://techcrunch.com/wp-content/uploads/2015/04/codecode.jpg?w=990&crop=1', max_length=500),
        ),
    ]
